services:
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-dev
    ports:
      - "4200:4200"  # Expone el puerto de ng serve
    volumes:
      - .:/app       # Monta tu carpeta local al contenedor
      - /app/node_modules  # Evita conflictos con node_modules locales
    stdin_open: true
    tty: true
    command: >
      sh -c "
      if [ ! -f package.json ]; then
        echo 'Creando proyecto Angular...';
        ng new angular-app --defaults --skip-git --directory .;
      fi;
      echo 'Iniciando Angular...';
      ng serve --host 0.0.0.0 --disable-host-check --poll 2000
      "
